version: "3"
services:
  bitcoind:
    image: fractalbitcoin/fractal:v0.2.9rc2
    entrypoint: ["bitcoind", "-datadir=/data/"]
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
    volumes:
      - ./data:/data
